### ISSUE TITLE
How to install from webadmin correctly

### ISSUE THREAD

**Issue by j8ter** [YunoHost-Apps/icecoder_ynh#35]
### Describe the bug

It might be me, but I do not understand the procedure of installing icecoder via Yunohost. After selecting the domain on which to install Icecoder, the webadmin requires me to fill in:

'Indicate the ID of the Custom Webapp where you want to install this app' (You can get the ID in Custom Webapp's settings)
'Indicate the name of the final_path subfolder containing the files accessible from your browser (For example for Custom Webapp it is located in the /www subfolder)

Do I first need to install Icecoder manually on my RPi and if so, with which requirements/steps to take to then install this Yunohost-packaged app?

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.3 (stable)
- I have access to my server: Through SSH & through the webadmin

**Comment by yalh76** [comment]
Icecoder is made to edit a website, in yunohost, better start is to have a Custom Webapp site installed and use icecoder to edit it

**Comment by j8ter** [comment]
Ah apologies, I didn't know about their relation, that makes sense. Thanks!
